apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: myprofile.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8s-front-svc
            port:
              number: 80

